apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts/
    clusterName: kind
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: minikube
    registry: 10.106.49.197
  environments:
  - key: dev
    owner: lindelani-nthangeni
    repository: jx3-dev-cluster
  - key: staging
  - key: production
  ingress:
    domain: 192.168.99.100.nip.io
    externalDNS: false
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: lindelani.nthangeni@gmail.com
      enabled: false
      production: false
  pipelineUser:
    username: lindelani-nthangeni
  repository: bucketrepo
  secretStorage: local
  vault: {}
  webhook: lighthouse
