apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        lindelani-nthangeni/hello-world: true
        lindelani-nthangeni/jx3-dev-cluster: true
        lindelani-nthangeni/python-demo2: true
        lindelani-nthangeni/python-http: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: true
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        lindelani-nthangeni/hello-world: merge
        lindelani-nthangeni/jx3-dev-cluster: merge
        lindelani-nthangeni/python-demo2: merge
        lindelani-nthangeni/python-http: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - lindelani-nthangeni/jx3-dev-cluster
        - lindelani-nthangeni/hello-world
        - lindelani-nthangeni/python-demo2
        - lindelani-nthangeni/python-http
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - lindelani-nthangeni/jx3-dev-cluster
        - lindelani-nthangeni/hello-world
        - lindelani-nthangeni/python-demo2
        - lindelani-nthangeni/python-http
      target_url: http://dashboard-jx.192.168.99.100.nip.io
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
